		/* SELECT TABLE PROCEDURE */
CREATE procedure SELECT_DATA @Language nvarchar(100)
AS
IF @Language = 'tr'
	SELECT * FROM tbl_News WHERE Title LIKE 'tr%';
ELSE IF @Language = 'en'
	SELECT * FROM tbl_News WHERE Title LIKE 'en%'

GO

CREATE procedure SELECT_DICTIONARY @Language nvarchar(100)
AS
IF @Language = 'tr'
	SELECT tr FROM tbl_Dictionary 
ELSE IF @Language = 'en'
	SELECT en FROM tbl_Dictionary

GO


		/*EXECUTE PRODESURE*/
EXEC CREATE_DATABASE_NEWS 
EXEC CREATE_DATABASE_DICTIONARY
EXEC INSERT_DATABASE_NEWS
EXEC INSERT_DATABASE_DICTIONARY

EXEC SELECT_DATA @Language = 'tr'
EXEC SELECT_DATA @Language = 'en'

EXEC SELECT_DICTIONARY @Language = 'tr'
EXEC SELECT_DICTIONARY @Language = 'en'

		/*DROP PROCEDURE*/
/*
DROP PROCEDURE CREATE_DATABASE_NEWS 
DROP PROCEDURE CREATE_DATABASE_DICTIONARY
DROP PROCEDURE INSERT_DATABASE_NEWS
DROP PROCEDURE INSERT_DATABASE_DICTIONARY
*/
